import pandas as pd
import io
import re
from fpdf import FPDF
from datetime import datetime

def clean_text(text):
    """Menghapus artefak markdown dan spasi berlebih untuk PDF."""
    if not text:
        return ""
    # Hapus bold/italic markers
    text = text.replace("**", "").replace("__", "").replace("*", "").replace("_", "")
    # Hapus header markers (seperti ## atau ###)
    text = re.sub(r"#+\s+", "", text)
    # Hapus bullet points di awal baris
    text = re.sub(r"^\s*[-*+]\s+", "", text, flags=re.MULTILINE)
    # Hapus baris kosong berlebih
    text = re.sub(r"\n\s*\n", "\n", text)
    return text.strip()

def export_to_excel(df):
    """Mengubah dataframe menjadi file Excel di memori (untuk download)."""
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Comps_Table')
    return output.getvalue()

class FinancialPDF(FPDF):
    def header(self):
        # Header bergaya laporan institusi
        self.set_font('helvetica', 'B', 15)
        self.set_text_color(44, 62, 80)
        self.cell(0, 10, 'EQUITY RESEARCH: COMPARABLE COMPANY ANALYSIS', 0, 1, 'L')
        self.set_draw_color(44, 62, 80)
        self.line(10, 20, 200, 20)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
        self.cell(0, 10, f'Generated by EQ_RES_TERMINAL | {date_str} | Page {self.page_no()}', 0, 0, 'C')

def generate_pdf_report(target_name, dna, comps_df, valuation_res):
    """Membuat laporan PDF profesional bergaya Financial Modelling dengan detail lebih banyak."""
    pdf = FinancialPDF()
    pdf.add_page()
    
    # --- 1. EXECUTIVE SUMMARY & VALUATION ---
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_fill_color(44, 62, 80)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 10, f' TARGET PROFILE: {target_name.upper()}', 0, 1, 'L', True)
    pdf.ln(5)
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(0, 8, 'SECTION I: VALUATION HIGHLIGHTS', 0, 1, 'L')
    pdf.set_font('helvetica', '', 10)
    
    col_width = 70
    metrics = [
        ("Implied Enterprise Value (Median)", f'${valuation_res["Implied EV (Bn)"]} Billion'),
        ("Median EV/Revenue Multiple", f'{valuation_res["Median Multiple"]}x'),
        ("Total Peers Analyzed", f'{len(comps_df)} Companies'),
        ("Analysis Date", datetime.now().strftime("%Y-%m-%d"))
    ]
    
    for label, value in metrics:
        pdf.set_font('helvetica', '', 10)
        pdf.cell(col_width, 7, label, 0, 0)
        pdf.set_font('helvetica', 'B', 10)
        pdf.cell(0, 7, value, 0, 1)
    pdf.ln(5)

    # --- 2. DETAILED BUSINESS DNA ---
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(0, 8, 'SECTION II: STRATEGIC BUSINESS ANALYSIS (AI-DRIVEN)', 0, 1, 'L')
    
    # Clean DNA text and split into sections for cleaner rendering
    cleaned_dna = clean_text(dna)
    pdf.set_font('helvetica', '', 9)
    pdf.multi_cell(0, 5, cleaned_dna)
    pdf.ln(10)

    # --- 3. PEER UNIVERSE TABLE ---
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(0, 8, 'SECTION III: COMPARABLE COMPANIES UNIVERSE', 0, 1, 'L')
    
    # Table Header
    pdf.set_font('helvetica', 'B', 8)
    pdf.set_fill_color(44, 62, 80)
    pdf.set_text_color(255, 255, 255)
    
    headers = ['TICKER', 'NAME', 'SCORE', 'EV/REV', 'EV/EBITDA', 'GROWTH %']
    widths = [20, 60, 20, 30, 30, 30]
    
    for i in range(len(headers)):
        pdf.cell(widths[i], 8, headers[i], 1, 0, 'C', True)
    pdf.ln()
    
    # Table Rows
    pdf.set_font('helvetica', '', 8)
    pdf.set_text_color(0, 0, 0)
    
    for _, row in comps_df.iterrows():
        # Zebra striping
        if _ % 2 == 0:
            pdf.set_fill_color(245, 245, 245)
        else:
            pdf.set_fill_color(255, 255, 255)
            
        pdf.cell(widths[0], 7, str(row['Ticker']), 1, 0, 'C', True)
        pdf.cell(widths[1], 7, str(row['Name'])[:35], 1, 0, 'L', True)
        pdf.cell(widths[2], 7, str(row['Score']), 1, 0, 'C', True)
        pdf.cell(widths[3], 7, f"{row['EV/Revenue']}x", 1, 0, 'R', True)
        pdf.cell(widths[4], 7, f"{row['EV/EBITDA']}x", 1, 0, 'R', True)
        pdf.cell(widths[5], 7, f"{row['Rev Growth (%)']}%", 1, 0, 'R', True)
        pdf.ln()
    
    pdf.ln(10)

    # --- 4. DETAILED AI RATIONALE ---
    pdf.add_page()
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(0, 8, 'SECTION IV: QUALITATIVE PEER COMPARISON RATIONALE', 0, 1, 'L')
    pdf.ln(2)
    
    for _, row in comps_df.iterrows():
        pdf.set_font('helvetica', 'B', 9)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(0, 6, f" {row['Ticker']} - {row['Name']}", 0, 1, 'L', True)
        
        pdf.set_font('helvetica', 'B', 8)
        pdf.cell(25, 5, "Similarity Score:", 0, 0)
        pdf.set_font('helvetica', '', 8)
        pdf.cell(0, 5, f"{row['Score']}/100", 0, 1)
        
        pdf.set_font('helvetica', 'B', 8)
        pdf.cell(25, 5, "AI Analysis:", 0, 0)
        pdf.set_font('helvetica', '', 8)
        pdf.multi_cell(0, 5, clean_text(row['Rationale']))
        pdf.ln(4)

    # --- 5. METHODOLOGY & DISCLAIMER ---
    pdf.ln(10)
    pdf.set_font('helvetica', 'B', 10)
    pdf.cell(0, 8, 'SECTION V: METHODOLOGY & LIMITATIONS', 0, 1, 'L')
    pdf.set_font('helvetica', '', 8)
    methodology = (
        "This report uses a hybrid AI-Quantitative approach. The Comparable Company Analysis (CCA) "
        "is built by: (1) Dynamic peer discovery via financial APIs, (2) AI-driven Business DNA "
        "extraction using LLMs, and (3) Similarity scoring based on monetization models and unit economics. "
        "Valuation multiples are sourced from real-time market data."
    )
    pdf.multi_cell(0, 5, methodology)
    
    # Return as bytes instead of bytearray for Streamlit compatibility
    return bytes(pdf.output())
